[build]
builder = "dockerfile"
buildCommand = ""

[deploy]
startCommand = ""
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[build.args]
BUILDKIT_INLINE_CACHE = "1"

[service]
timeout = 3600

[env]
PYTHON_VERSION = "3.9"
